/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fc_bff;

import Conexion.Conexion;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;

/**
 *
 * @author javie
 */
public class CHATuno extends javax.swing.JFrame {

    /**
     * Creates new form CHAT
     */
    Conexion cc = new Conexion();
    Connection con = cc.getConnection();

    public CHATuno() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imgbff/ig6.png")));
        jScrollPane2.getVerticalScrollBar().setUnitIncrement(20);
        mostrarDatos();
        Tarea tarea = new Tarea();
        Timer temporizador = new Timer();
        Integer segundos = 10;

        temporizador.scheduleAtFixedRate(tarea, 0, 100 * segundos);
    }

    public class Tarea extends TimerTask {
//static private final Logger LOGGER = Logger.getLogger("mx.com.hash.tareaprogramada.Tarea");

        private Integer contador;

        public Tarea() {
            contador = 0;
        }

        @Override
        public void run() {
            mostrarDatos();
            contador++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        INPUT = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        BTNENVIAR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        alert = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        VENTANACHAT = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("APP-BFF");
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(390, 503));

        INPUT.setColumns(3);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgbff/iniciar2.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BTNENVIAR.setText("ENVIAR");
        BTNENVIAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTNENVIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNENVIARActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("CHATCITO");

        VENTANACHAT.setEditable(false);
        VENTANACHAT.setColumns(20);
        VENTANACHAT.setLineWrap(true);
        VENTANACHAT.setRows(5);
        jScrollPane2.setViewportView(VENTANACHAT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(alert, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNENVIAR, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNENVIAR))
                .addGap(18, 18, 18)
                .addComponent(alert, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNENVIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNENVIARActionPerformed
        // TODO add your handling code here:

//        alert.setText("");
        if ((INPUT.getText()).equals("")) {
            alert.setText("INGRESE UN MENSAJE");
        } else {
            insertarDatos();
            limpiarCajas();
            mostrarDatos();
            alert.setText("MENSAJE ENVIADO");
        }
    }//GEN-LAST:event_BTNENVIARActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MENUPRINCIPAL menuprincipal = new MENUPRINCIPAL();

        menuprincipal.setVisible(true);
        //centrar la ventana
        menuprincipal.setLocationRelativeTo(null);
        //cierra la ventana
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    public void mostrarDatos() {
        String SQL = "SELECT * FROM chat ORDER BY fecha ASC;";
        String f = "";
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            //referencia a las cominas de la base de datos
            while (rs.next()) {
                f = f + rs.getString("nameuser");
                f = f + rs.getString("msg");
                f = f + "\n";
                f = f + "\n";
            }
            VENTANACHAT.setText(f);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al mostrar datos" + e.getMessage());
            MENUPRINCIPAL menuprincipal = new MENUPRINCIPAL();
            menuprincipal.setVisible(true);
            //centrar la ventana
            menuprincipal.setLocationRelativeTo(null);
            //cierra la ventana
            this.dispose();
        }
    }

    public void insertarDatos() {
        String x = "Javier: ";
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        String c = dtf.format(LocalDateTime.now());
        try {
            String SQL = "insert into chat (nameuser,msg,fecha) values(?,?,?)";
            PreparedStatement pst = con.prepareStatement(SQL);
            pst.setString(1, x);
            pst.setString(2, INPUT.getText());
            pst.setString(3, c);
            pst.execute();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error..." + e.getMessage());
        }
    }

    public void limpiarCajas() {
        INPUT.setText(" ");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CHATuno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CHATuno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CHATuno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CHATuno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CHATuno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNENVIAR;
    private javax.swing.JTextField INPUT;
    private javax.swing.JTextArea VENTANACHAT;
    private javax.swing.JLabel alert;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
